-- Seed data for the diagnoses table (ICD-10-CM billable codes)
-- Source: https://www.icd10data.com/ICD10CM/Codes

INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.00', 'Diabetes mellitus due to underlying condition with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.01', 'Diabetes mellitus due to underlying condition with hyperosmolarity with coma') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.10', 'Diabetes mellitus due to underlying condition with ketoacidosis without coma') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.11', 'Diabetes mellitus due to underlying condition with ketoacidosis with coma') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.21', 'Diabetes mellitus due to underlying condition with diabetic nephropathy') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.22', 'Diabetes mellitus due to underlying condition with diabetic chronic kidney disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.29', 'Diabetes mellitus due to underlying condition with other diabetic kidney complication') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.311', 'Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy with macular edema') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.319', 'Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy without macular edema') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('E08.3211', 'Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, right eye') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I10', 'Essential (primary) hypertension') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I11.0', 'Hypertensive heart disease with heart failure') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I11.9', 'Hypertensive heart disease without heart failure') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I13.0', 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I13.10', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('I15.0', 'Renovascular hypertension') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J00', 'Acute nasopharyngitis [common cold]') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.00', 'Acute maxillary sinusitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.01', 'Acute recurrent maxillary sinusitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.10', 'Acute frontal sinusitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.11', 'Acute recurrent frontal sinusitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.20', 'Acute ethmoidal sinusitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.21', 'Acute recurrent ethmoidal sinusitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.30', 'Acute sphenoidal sinusitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.31', 'Acute recurrent sphenoidal sinusitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J01.40', 'Acute pansinusitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J69.0', 'Pneumonitis due to inhalation of food and vomit') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J69.1', 'Pneumonitis due to inhalation of oils and essences') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J69.8', 'Pneumonitis due to inhalation of other solids and liquids') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J09.X1', 'Influenza due to identified novel influenza A virus with pneumonia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J09.X2', 'Influenza due to identified novel influenza A virus with other respiratory manifestations') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J09.X3', 'Influenza due to identified novel influenza A virus with gastrointestinal manifestations') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J09.X9', 'Influenza due to identified novel influenza A virus with other manifestations') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J10.00', 'Influenza due to other identified influenza virus with unspecified type of pneumonia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J10.01', 'Influenza due to other identified influenza virus with the same other identified influenza virus pneumonia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('J10.08', 'Influenza due to other identified influenza virus with other specified pneumonia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K44.0', 'Diaphragmatic hernia with obstruction, without gangrene') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K44.1', 'Diaphragmatic hernia with gangrene') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K44.9', 'Diaphragmatic hernia without obstruction or gangrene') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K20.0', 'Eosinophilic esophagitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K20.80', 'Other esophagitis without bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K20.81', 'Other esophagitis with bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K20.90', 'Esophagitis, unspecified without bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K20.91', 'Esophagitis, unspecified with bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K21.00', 'Gastro-esophageal reflux disease with esophagitis, without bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('K21.01', 'Gastro-esophageal reflux disease with esophagitis, with bleeding') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.00', 'Cervical disc disorder with myelopathy, unspecified cervical region') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.01', 'Cervical disc disorder with myelopathy, high cervical region') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.020', 'Cervical disc disorder with myelopathy, mid-cervical region, unspecified level') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.021', 'Cervical disc disorder at C4-C5 level with myelopathy') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.022', 'Cervical disc disorder at C5-C6 level with myelopathy') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.023', 'Cervical disc disorder at C6-C7 level with myelopathy') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.03', 'Cervical disc disorder with myelopathy, cervicothoracic region') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.10', 'Cervical disc disorder with radiculopathy, unspecified cervical region') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.11', 'Cervical disc disorder with radiculopathy, high cervical region') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('M50.120', 'Mid-cervical disc disorder, unspecified level') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.00', 'Acute cystitis without hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.01', 'Acute cystitis with hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.10', 'Interstitial cystitis (chronic) without hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.11', 'Interstitial cystitis (chronic) with hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.20', 'Other chronic cystitis without hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.21', 'Other chronic cystitis with hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.30', 'Trigonitis without hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.31', 'Trigonitis with hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.40', 'Irradiation cystitis without hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('N30.41', 'Irradiation cystitis with hematuria') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.0', 'Besnier''s prurigo') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.81', 'Atopic neurodermatitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.82', 'Flexural eczema') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.83', 'Infantile (acute) (chronic) eczema') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.84', 'Intrinsic (allergic) eczema') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.89', 'Other atopic dermatitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L20.9', 'Atopic dermatitis, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L21.0', 'Seborrhea capitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L21.1', 'Seborrheic infantile dermatitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('L21.8', 'Other seborrheic dermatitis') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.00', 'Agoraphobia, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.01', 'Agoraphobia with panic disorder') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.02', 'Agoraphobia without panic disorder') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.10', 'Social phobia, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.11', 'Social phobia, generalized') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.210', 'Arachnophobia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.218', 'Other animal type phobia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.220', 'Fear of thunderstorms') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.228', 'Other natural environment type phobia') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('F40.230', 'Fear of blood') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.2', 'Drug induced fever') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.81', 'Fever presenting with conditions classified elsewhere') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.82', 'Postprocedural fever') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.83', 'Postvaccination fever') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.84', 'Febrile nonhemolytic transfusion reaction') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R50.9', 'Fever, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R51.0', 'Headache with orthostatic component, not elsewhere classified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R51.9', 'Headache, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R52', 'Pain, unspecified') ON CONFLICT (icd10_code) DO NOTHING;
INSERT INTO diagnoses (icd10_code, description) VALUES ('R53.0', 'Neoplastic (malignant) related fatigue') ON CONFLICT (icd10_code) DO NOTHING;
